name: CI
on: 
  push:
    branches:
      - main #here we choose to deploy only when a push is detected on the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Setup AWS CLI
      run: |
        apt-get update
        apt-get install -y python3-pip
        pip3 install awscli
    - name: Configure AWS Credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws configure set default.region us-west-1
        
    # Here you could add some building steps if you were dealing with some angular/react/Vue...
    # - name: Build static site
    #  run: yarn install && npm run-script build
    
    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://thisiskevinstest.com --delte --exclude ".git/*" 
      # --delete flag will remove any file in the s3 that are not on the "thefoldertodeploy" folder
